### PR TITLE
Add option existingModule

### PR DESCRIPTION
**Pull request by Jandalf**
so it will use an existing module instead of creating a new one.

### CODE REVIEW

**Comment by npx** [comment]
What's the status on this? I want this :3

**Comment by Jandalf** [comment]
no activity from the author in the last 20 days...

**Comment by karlgoldstein** [comment]
Sorry for the delay.

Published to NPM as 0.3.4

**Comment by npx** [comment]
@karlgoldstein Thank you for reacting promptly :3 You just made my life a lot easier!

**Pull request merged**
